'######beta': 0.9999
'######epochs': 100
'######gamma': 0.5
'######loss_ratio': 0.9
'######model_ emb_size': 16
'######model_dim_ff': 256
'######model_dropout': 0.1
'######model_num_heads': 8
'#####batch_size': 512
'#####learning_rate': 0.0001
batch_size: 512
beta: 0.9999
data_path: ./data/001goat.pt
epochs: 100
gamma: 0.5
gpu: 1
learning_rate: 0.0001
loss_ratio: 0.9
model_Fix_pos_encode: tAPE
model_Rel_pos_encode: ePRE
model_channel_size: 3
model_dim_ff: 256
model_dropout: 0.1
model_emb_size: 16
model_num_heads: 8
model_seq_len: 50
network: ConvTrans
save_path: setting0
seed: 10
weight_decay: 0.004
