'######beta': 0.9999
'######epochs': 100
'######gamma': 0.5
'######loss_ratio': 0.9
'#####batch_size': 512
'#####learning_rate': 0.0001
batch_size: 512
beta: 0.9999
data_path: ./data/00goat.pt
epochs: 100
gamma: 0.5
gpu: 1
learning_rate: 0.0001
loss_ratio: 0.9
network: ConvTrans
save_path: setting0
seed: 10
weight_decay: 0.004
