batch_size: 256
beta: 0.9999
data_path: E:\program\aaa_DL_project\0000PatchTST-TFC\CMI-Net\data\new_goat_25hz_3axis.pt
epochs: 50
gamma: 3.0
gpu: 1
learning_rate: 0.0001
model_affine: false
model_classifier_dropout: 0.5
model_conv1d_kernel_size: 3
model_conv1d_out_channels: 32
model_d_ff: 256
model_d_model: 128
model_decomposition: false
model_dropout: 0.2
model_e_layers: 2
model_enc_in: 3
model_fc_dropout: 0.2
model_head_dropout: 0.2
model_individual: false
model_kernel_size: 25
model_n_heads: 8
model_num_classes: 5
model_padding_patch: end
model_patch_len: 8
model_pred_len: 24
model_revin: false
model_seq_len: 50
model_stride: 4
model_subtract_last: false
model_use_weighted_loss: false
network: PatchTST_wyh
save_path: setting0
seed: 10
weight_decay: 0.001
