model_name: PatchTST
model_architecture:
  layers:
  - name: model
    type: PatchTST_backbone
    parameters: 455761
  - name: classifier
    type: Sequential
    parameters: 39941
  total_parameters: 495702
  trainable_parameters: 495699
training_config:
  batch_size: 128
  learning_rate: 0.001
  epochs: 100
  seed: 10
  weight_decay: 1.0e-05
  beta: 0.9999
  gamma: 2.5
  gpu: true
  optimizer: AdamW
  loss_function: CB_loss with focal
  scheduler: LambdaLR with warmup and cosine decay
performance_metrics:
  best_accuracy: 0
  best_epoch: 0
  final_metrics:
    accuracy: 0
    f1_score: 0
    precision: 0
    recall: 0
    kappa: 0
